// src/data/edukasiContent.js

import ranteAnim from '../assets/modal/rante.json';
import shieldAnim from '../assets/modal/shield.json';
import warningAnim from '../assets/modal/warning.json';

export const edukasiData = [
  { id: 1, tagline: "DASAR-DASAR ANCAMAN", title: "Membedah Anatomi Phishing", description: "Pahami bagaimana penipu merancang jebakan mereka, mulai dari email palsu hingga situs web yang meniru aslinya.", detail: `Phishing adalah upaya penipuan untuk mendapatkan informasi sensitif Anda, seperti kata sandi, detail kartu kredit, atau data pribadi lainnya, dengan menyamar sebagai entitas terpercaya dalam komunikasi elektronik.\n\nTujuan utamanya adalah menipu Anda agar secara sukarela memberikan informasi tersebut.\n\nModus Umum Phishing:\n- Email dari "bank" yang menyatakan ada masalah dengan akun Anda dan meminta Anda login melalui link yang mereka berikan.\n- Pesan WhatsApp mengatasnamakan kurir paket yang meminta Anda meng-install aplikasi (.apk) untuk melacak paket.\n- Situs web palsu yang meniru halaman login Instagram atau Google untuk mencuri username dan password Anda.\n- Tawaran hadiah atau diskon yang tidak masuk akal yang mengharuskan Anda mengisi formulir dengan data pribadi.`, icon: "📨" },
  { id: 2, tagline: "INVESTIGASI DIGITAL", title: "Mendeteksi Jebakan dalam URL", description: "Belajar menjadi detektif digital dengan mengenali tanda-tanda bahaya dalam sebuah tautan sebelum Anda mengkliknya.", detail: `URL adalah petunjuk terbesar. Perhatikan baik-baik sebelum mengklik.\n\nTanda Bahaya pada URL:\n- Salah Eja (Typo): Perhatikan domain utama. Penipu sering menggunakan nama yang sangat mirip, misal: 'klikbca.com' (benar) vs 'klik-bca.co' atau 'kllikbca.com' (palsu).\n- Subdomain Menyesatkan: Dalam 'secure.bank-anda.com.xyz', domain utamanya adalah 'com.xyz', bukan 'bank-anda.com'. Domain yang sah selalu berada tepat sebelum .com, .co.id, dll.\n- Karakter Aneh atau Simbol: URL yang sah jarang menggunakan banyak simbol hubung (-) atau karakter yang tidak biasa.\n- Bukan HTTPS: Jika sebuah situs web meminta data login tapi alamatnya dimulai dengan 'http://' bukan 'https://🔒', itu adalah bendera merah raksasa. Namun, HTTPS saja bukan jaminan 100% aman.`, icon: "🔗" },
  { id: 3, tagline: "DAMPAK & RISIKO", title: "Konsekuensi dari Satu Klik", description: "Ketahui risiko nyata yang terjadi setelah mengklik link berbahaya, dari pencurian identitas hingga infeksi malware.", detail: `Kerusakan dari satu klik yang salah bisa sangat masif dan menyebar dengan cepat.\n\nBeberapa Konsekuensi Fatal:\n- Kehilangan Akses Akun: Akun email atau media sosial Anda bisa diambil alih dan digunakan untuk menipu kontak Anda.\n- Kerugian Finansial: Kredensial mobile banking atau detail kartu kredit Anda dicuri, lalu isi rekening Anda dikuras habis.\n- Instalasi Malware/Ransomware: Perangkat Anda (HP atau laptop) bisa terinfeksi virus yang mencuri data atau bahkan mengunci semua file Anda dan meminta tebusan (ransomware).\n- Pencurian Identitas: Data pribadi Anda (KTP, KK) digunakan untuk melakukan pinjaman online ilegal atau kejahatan lain atas nama Anda.`, icon: "⚠️" },
  { id: 4, tagline: "STRATEGI PERTAHANAN", title: "Membangun Benteng Digital Anda", description: "Terapkan langkah-langkah proaktif seperti 2FA dan kebiasaan digital yang aman untuk menjadi target yang sulit ditembus.", detail: `Menjadi korban phishing seringkali bisa dicegah dengan kebiasaan yang baik.\n\nStrategi Pertahanan Anda:\n- Mantra Utama: "Jangan Percaya, Selalu Verifikasi". Jika ada pesan yang mendesak atau mencurigakan, hubungi perusahaan terkait melalui jalur resmi (telepon atau website resmi), jangan melalui link di pesan tersebut.\n- Aktifkan 2FA (Autentikasi Dua Faktor): Ini adalah lapisan keamanan terpenting. Bahkan jika password Anda dicuri, penipu tidak bisa masuk tanpa kode dari HP Anda.\n- Gunakan Password Manager: Buat password yang unik dan rumit untuk setiap akun. Mustahil untuk mengingat semuanya, jadi gunakan aplikasi password manager terpercaya.\n- Selalu Update Perangkat Lunak: Pastikan browser, sistem operasi HP, dan laptop Anda selalu dalam versi terbaru untuk mendapatkan patch keamanan terkini.\n- Berpikir Sebelum Klik: Tanyakan pada diri sendiri, "Apakah saya mengharapkan email ini? Apakah tawarannya terlalu bagus untuk jadi kenyataan?"`, icon: "🛡️" },
];

export const animMap = {
  "Membedah Anatomi Phishing": null,
  "Mendeteksi Jebakan dalam URL": ranteAnim,
  "Konsekuensi dari Satu Klik": warningAnim,
  "Membangun Benteng Digital Anda": shieldAnim,
};